services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=shortener'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'

  adminer:
    image: adminer
    container_name: adminer-tool
    restart: always
    ports:
      - '8081:8080'
    depends_on:
      - postgres