CREATE TABLE access (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    userAgent VARCHAR(255) NOT NULL,
    accessDate TIMESTAMP NOT NULL,
    zone VARCHAR(255) NOT NULL,
    url_id INTEGER REFERENCES url(id)
)